apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-conversao
spec:
  #replicas: 2
  selector:
    matchLabels:
      app: api-conversao
  template:
    metadata:
      labels:
        app: api-conversao
    spec:
      containers:
        - name: api-conversao
          image: robsoncruz/api-conversao:v1
          ports:
            - containerPort: 8080
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 3
            periodSeconds: 2
            timeoutSeconds: 1
            successThreshold: 1
            failureThreshold: 1
          readinessProbe:
            httpGet:
              path: /ready
              port: 8080
            initialDelaySeconds: 3
            periodSeconds: 2
            timeoutSeconds: 1
            successThreshold: 1
            failureThreshold: 1
          resources:
            requests:
              cpu: "200m"
              memory: "32Mi"
            limits:
              cpu: "400m"
              memory: "64Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: api-conversao-service
spec:
  selector:
    app: api-conversao
  ports:
    - port: 80 # porta do serviço
      targetPort: 8080 # porta do container
      nodePort: 30000
  type: NodePort #LoadBalancer

---
# AutoScaling :)
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: api-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: api-conversao
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 60

#Example stress test
#[PUT] http://localhost:8080/stress/cpu/tempostress/60/intervalo/1/ciclos/2