apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-conversao
spec:
  replicas: 4
  selector:
    matchLabels:
      app: api-conversao
  template:
    metadata:
      labels:
        app: api-conversao
    spec:
      containers:
        - name: api-conversao
          image: robsoncruz/api-conversao:v1
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: api-conversao-service
spec:
  selector:
    app: api-conversao
  ports:
    - port: 80 # porta do serviço
      targetPort: 8080 # porta do container
      nodePort: 30000
  type: NodePort